[general]
output = "output"
pidfn = "default_pid"
primfn = "default_primary_classification"

[[category]] # 0 : Cosmic mu- to e-
cuts = [
    { name = "!neutrino" },
    { name = "is_michel_pdg", parameter = [11, 8.7] },
]

[[category]] # 1 : Cosmic mu- to e-
cuts = [
    { name = "!neutrino" },
    { name = "is_michel_pdg", parameters = [-11, 8.7] },
]

[[category]] # 2 : offbeam gamma
cuts = [
    { name = "!neutrino" },
    { name = "is_michel_pdg",   parameters = [22, 8.7]  },
]

[[category]] # 3 : other cosmics
cuts = [
    { name = "!neutrino" },
    { name = "!is_michel_pdg",  parameters = [11, 8.7]  },
    { name = "!is_michel_pdg",  parameters = [-11, 8.7] },
    { name = "!is_michel_pdg",  parameters = [22, 8.7]  },
]

[[category]] # 4 : beam
cuts = [
    { name = "neutrino" },
]

[[sample]]
name = "nominal"
path = "/pnfs/icarus/persistent/users/mueller/production/simulation/nominal/input*.flat.root"
ismc = true
disable = false

[[tree]]
name = "selected"
sim_only = false
mode = "reco"
cut = [
    {name = "!valid_flashmatch", type = "reco"},
    {name = "michel_in_range",   type = "reco", parameters = [8.7]},
    {name = "michel_size",       type = "reco", parameters = [7, 8.7]},
]
branch = [
    {name = "neutrino_id",   type = "true"},
    {name = "semantic_type", type = "both_particle", selector = "target_michel", parameter = [8.7]},
    {name = "iou",           type = "both_particle", selector = "target_michel", parameter = [8.7]},
    {name = "ke",            type = "both_particle", selector = "target_michel", parameter = [8.7]},
    {name = "calo_ke",       type = "reco_particle", selector = "target_michel", parameter = [8.7]},
]

[[tree]]
name = "signal"
sim_only = false
mode = "reco"
cut = [
    {name = "!valid_flashmatch", type = "reco"},
    {name = "michel_in_range",   type = "true", parameters = [8.7]},
    {name = "michel_size",       type = "true", parameters = [7, 8.7]},
]
branch = [
    {name = "neutrino_id",   type = "true"},
    {name = "semantic_type", type = "both_particle", selector = "target_michel", parameter = [8.7]},
    {name = "iou",           type = "both_particle", selector = "target_michel", parameter = [8.7]},
    {name = "ke",            type = "both_particle", selector = "target_michel", parameter = [8.7]},
    {name = "calo_ke",       type = "reco_particle", selector = "target_michel", parameter = [8.7]},
]