[general]
output = "output"
pidfn = "default_pid"
primfn = "default_primary_classification"

[[category]] # 0 : Cosmic mu- to e-, single cluster
cuts = [
    { name = "!neutrino"  },
    { name = "!no_michel" },
    { name = "!no_primary_muon"   },
    { name = "single_michel_cluster"},
    { name = "is_michel_pdg",     parameters = [11.0] },
]

[[category]] # 1 : Cosmic mu- to e-, single cluster
cuts = [
    { name = "!neutrino" },
    { name = "!no_michel" },
    { name = "!no_primary_muon"   },
    { name = "single_michel_cluster"},
    { name = "is_michel_pdg",     parameters = [-11.0] },
]

[[category]] # 2 : Cosmic e-gamma, single cluster
cuts = [
    { name = "!neutrino" },
    { name = "!no_michel" },
    { name = "!no_primary_muon"   },
    { name = "single_michel_cluster"},
    { name = "is_michel_pdg",     parameters = [22.0] },
]

[[category]] # 3 : Cosmic mu- to e- non single cluster
cuts = [
    { name = "!neutrino"  },
    { name = "!no_michel" },
    { name = "!no_primary_muon"   },
    { name = "!single_michel_cluster"},
    { name = "is_michel_pdg",     parameters = [11.0] },
]

[[category]] # 4 : Cosmic mu- to e-, non single cluster
cuts = [
    { name = "!neutrino" },
    { name = "!no_michel" },
    { name = "!no_primary_muon"   },
    { name = "!single_michel_cluster"},
    { name = "is_michel_pdg",     parameters = [-11.0] },
]

[[category]] # 5 : Cosmic e-gamma, non  single cluster
cuts = [
    { name = "!neutrino" },
    { name = "!no_michel" },
    { name = "!no_primary_muon"   },
    { name = "!single_michel_cluster"},
    { name = "is_michel_pdg",     parameters = [22.0] },
]

[[category]] # 6 : no true primary muon
cuts = [
    { name = "!neutrino" },
    { name = "!no_michel" },
    { name = "no_primary_muon"   },
]

[[category]] # 7 : no true michel
cuts = [
    { name = "!neutrino" },
    { name = "no_michel" },
]

[[category]] # 8 : beam
cuts = [
    { name = "neutrino" },
]

[[sample]]
name = "nominal"
path = "/pnfs/icarus/persistent/users/mueller/production/simulation/nominal/input*.flat.root"
ismc = true
disable = false

[[tree]]
name = "selected"
sim_only = false
mode = "reco"
cut = [
    {name = "!valid_flashmatch", type = "reco"},
    {name = "michel_in_range",   type = "reco", parameters = [8.7]},
    {name = "michel_size",       type = "reco", parameters = [7.0]},
]
branch = [
    {name = "neutrino_id",   type = "true"},
    {name = "category",      type = "true"},
    {name = "selected_michel_muon_gap", type = "both" },

    {name = "semantic_type", type = "both_particle", selector = "target_michel"},
    {name = "iou",           type = "both_particle", selector = "target_michel"},
    {name = "ke",            type = "both_particle", selector = "target_michel"},
    {name = "calo_ke",       type = "reco_particle", selector = "target_michel"},
    {name = "pdg",           type = "true_particle", selector = "target_michel"},

    {name = "start_x",      type = "both_particle", selector = "target_michel" },
    {name = "start_y",      type = "both_particle", selector = "target_michel" },
    {name = "start_z",      type = "both_particle", selector = "target_michel" },

    {name = "end_x",        type = "both_particle", selector = "target_michel_parent" },
    {name = "end_y",        type = "both_particle", selector = "target_michel_parent" },
    {name = "end_z",        type = "both_particle", selector = "target_michel_parent" },

    {name = "self_id",      type = "both_particle", selector = "target_michel" },
    {name = "parent_id",    type = "both_particle", selector = "target_michel" },
    {name = "self_id",      type = "both_particle", selector = "target_michel_parent" },
    {name = "parent_id",    type = "both_particle", selector = "target_michel_parent" },

    {name = "primary_softmax", type = "reco_particle", selector = "target_michel_parent" },

]

[[tree]]
name = "signal"
sim_only = true
mode = "true"
cut = [
    {name = "!valid_flashmatch", type = "reco"},
    {name = "michel_in_range",   type = "true", parameters = [8.7]},
    {name = "michel_size",       type = "true", parameters = [7.0]},
]
branch = [
    {name = "neutrino_id",   type = "true"},
    {name = "category",      type = "true"},
    {name = "selected_michel_muon_gap", type = "true" },

    {name = "semantic_type", type = "both_particle", selector = "target_michel" },
    {name = "iou",           type = "both_particle", selector = "target_michel" },
    {name = "ke",            type = "both_particle", selector = "target_michel" },
    {name = "calo_ke",       type = "reco_particle", selector = "target_michel" },
    {name = "pdg",           type = "true_particle", selector = "target_michel" },

    {name = "start_x",      type = "both_particle", selector = "target_michel" },
    {name = "start_y",      type = "both_particle", selector = "target_michel" },
    {name = "start_z",      type = "both_particle", selector = "target_michel" },

    {name = "end_x",        type = "both_particle", selector = "target_michel_parent" },
    {name = "end_y",        type = "both_particle", selector = "target_michel_parent" },
    {name = "end_z",        type = "both_particle", selector = "target_michel_parent" },

    {name = "self_id",      type = "both_particle", selector = "target_michel" },
    {name = "parent_id",    type = "both_particle", selector = "target_michel" },
    {name = "self_id",      type = "both_particle", selector = "target_michel_parent" },
    {name = "parent_id",    type = "both_particle", selector = "target_michel_parent" },

    {name = "primary_softmax", type = "reco_particle", selector = "target_michel_parent" },

]