[general]
output = "output"
pidfn = "default_pid"
primfn = "default_primary_classification"

[[category]] # 0 : Cosmic mu- to e-
cuts = [
    { name = "!neutrino" },
    { name = "is_michel_pdg", parameter = [11.0, 8.7] },
]

[[category]] # 1 : Cosmic mu- to e-
cuts = [
    { name = "!neutrino" },
    { name = "is_michel_pdg", parameters = [-11.0, 8.7] },
]

[[category]] # 2 : offbeam gamma
cuts = [
    { name = "!neutrino" },
    { name = "is_michel_pdg",   parameters = [22.0, 8.7]  },
]

[[category]] # 3 : other cosmics
cuts = [
    { name = "!neutrino" },
    { name = "!is_michel_pdg",  parameters = [11.0, 8.7]  },
    { name = "!is_michel_pdg",  parameters = [-11.0, 8.7] },
    { name = "!is_michel_pdg",  parameters = [22.0, 8.7]  },
]

[[category]] # 4 : beam
cuts = [
    { name = "neutrino" },
]

[[sample]]
name = "onbeam"
path = "/pnfs/icarus/persistent/users/mueller/production/data/onbeam/input*.flat.root"
ismc = false
disable = false

[[sample]]
name = "offbeam"
path = "/pnfs/icarus/persistent/users/mueller/production/data/offbeam/input*.flat.root"
ismc = false
disable = false

[[sample]]
name = "nominal"
path = "/pnfs/icarus/persistent/users/mueller/production/simulation/nominal/input*.flat.root"
ismc = true
disable = false

[[sample]]
name = "cvext"
path = "/pnfs/icarus/persistent/users/mueller/production/simulation/cvext/input*.flat.root"
ismc = true
disable = false

[[sample]]
name = "var00"
path = "/pnfs/icarus/persistent/users/mueller/production/simulation/var00/input*.flat.root"
ismc = true
disable = true

[[sample]]
name = "var01"
path = "/pnfs/icarus/persistent/users/mueller/production/simulation/var01/input*.flat.root"
ismc = true
disable = true

[[sample]]
name = "var02"
path = "/pnfs/icarus/persistent/users/mueller/production/simulation/var02/input*.flat.root"
ismc = true
disable = true

[[sample]]
name = "var03m"
path = "/pnfs/icarus/persistent/users/mueller/production/simulation/var03m/input*.flat.root"
ismc = true
disable = true

[[sample]]
name = "var03p"
path = "/pnfs/icarus/persistent/users/mueller/production/simulation/var03p/input*.flat.root"
ismc = true
disable = true

[[sample]]
name = "var04"
path = "/pnfs/icarus/persistent/users/mueller/production/simulation/var04/input*.flat.root"
ismc = true
disable = true

[[sample]]
name = "var05"
path = "/pnfs/icarus/persistent/users/mueller/production/simulation/var05/input*.flat.root"
ismc = true
disable = true

[[sample]]
name = "var06"
path = "/pnfs/icarus/persistent/users/mueller/production/simulation/var06/input*.flat.root"
ismc = true
disable = true

[[sample]]
name = "var07"
path = "/pnfs/icarus/persistent/users/mueller/production/simulation/var07/input*.flat.root"
ismc = true
disable = true

[[sample]]
name = "var09m"
path = "/pnfs/icarus/persistent/users/mueller/production/simulation/var09m/input*.flat.root"
ismc = true
disable = true

[[sample]]
name = "var09p"
path = "/pnfs/icarus/persistent/users/mueller/production/simulation/var09p/input*.flat.root"
ismc = true
disable = true

[[sample]]
name = "var10m"
path = "/pnfs/icarus/persistent/users/mueller/production/simulation/var10m/input*.flat.root"
ismc = true
disable = true

[[sample]]
name = "var10p"
path = "/pnfs/icarus/persistent/users/mueller/production/simulation/var10p/input*.flat.root"
ismc = true
disable = true

[[sample]]
name = "var11"
path = "/pnfs/icarus/persistent/users/mueller/production/simulation/var11/input*.flat.root"
ismc = true
disable = true

[[sample]]
name = "var12m"
path = "/pnfs/icarus/persistent/users/mueller/production/simulation/var12m/input*.flat.root"
ismc = true
disable = true

[[sample]]
name = "var12p"
path = "/pnfs/icarus/persistent/users/mueller/production/simulation/var12p/input*.flat.root"
ismc = true
disable = true

[[sample]]
name = "var13m"
path = "/pnfs/icarus/persistent/users/mueller/production/simulation/var13m/input*.flat.root"
ismc = true
disable = true

[[sample]]
name = "var13p"
path = "/pnfs/icarus/persistent/users/mueller/production/simulation/var13p/input*.flat.root"
ismc = true
disable = true

[[tree]]
name = "selected"
sim_only = false
add_systematics = true
mode = "reco"
cut = [
    {name = "!valid_flashmatch", type = "reco"},
    {name = "michel_in_range",   type = "reco", parameters = [8.7]},
    {name = "michel_size",       type = "reco", parameters = [7.0, 8.7]},
]
branch = [
    {name = "neutrino_id",   type = "true"},
    {name = "semantic_type", type = "both_particle", selector = "target_michel"},
    {name = "iou",           type = "both_particle", selector = "target_michel"},
    {name = "ke",            type = "both_particle", selector = "target_michel"},
    {name = "calo_ke",       type = "reco_particle", selector = "target_michel"},
]

[[tree]]
name = "signal"
sim_only = false
mode = "reco"
cut = [
    {name = "!valid_flashmatch", type = "reco"},
    {name = "michel_in_range",   type = "true", parameters = [8.7]},
    {name = "michel_size",       type = "true", parameters = [7.0, 8.7]},
]
branch = [
    {name = "neutrino_id",   type = "true"},
    {name = "semantic_type", type = "both_particle", selector = "target_michel"},
    {name = "iou",           type = "both_particle", selector = "target_michel"},
    {name = "ke",            type = "both_particle", selector = "target_michel"},
    {name = "calo_ke",       type = "reco_particle", selector = "target_michel"},
]