[general]
output = "output"
pidfn = "default_pid"
primfn = "default_primary_classification"

[[category]] # 0 : Cosmic mu- to e-
cuts = [
    { name = "!neutrino"  },
    { name = "!no_michel" },
    { name = "!no_primary_muon"   },
    { name = "michel_in_range",   parameters = [8.7] },
    { name = "is_michel_pdg",     parameters = [11.0, 8.7] },
]

[[category]] # 1 : Cosmic mu- to e-
cuts = [
    { name = "!neutrino" },
    { name = "!no_michel" },
    { name = "!no_primary_muon"   },
    { name = "michel_in_range",   parameters = [8.7] },
    { name = "is_michel_pdg",   parameters = [-11.0, 8.7] },
]

[[category]] # 2 : offbeam gamma
cuts = [
    { name = "!neutrino" },
    { name = "!no_michel" },
    { name = "!no_primary_muon"   },
    { name = "michel_in_range",   parameters = [8.7] },
    { name = "is_michel_pdg",   parameters = [22.0, 8.7]  },
]

[[category]] # 3 : true primary out of range
cuts = [
    { name = "!neutrino" },
    { name = "!no_michel" },
    { name = "!no_primary_muon"   },
    { name = "!michel_in_range",   parameters = [8.7] },
]

[[category]] # 4 : no true primary muon
cuts = [
    { name = "!neutrino" },
    { name = "!no_michel" },
    { name = "no_primary_muon"   },
]

[[category]] # 5 : no true michel
cuts = [
    { name = "!neutrino" },
    { name = "no_michel" },
]

[[category]] # 6 : beam
cuts = [
    { name = "neutrino" },
]

[[sample]]
name = "nominal"
path = "/pnfs/icarus/persistent/users/mueller/production/simulation/nominal/input000.flat.root"
ismc = true
disable = false

[[tree]]
name = "selected"
sim_only = false
mode = "reco"
cut = [
    {name = "!valid_flashmatch", type = "reco"},
    {name = "michel_in_range",   type = "reco", parameters = [8.7]},
    {name = "michel_size",       type = "reco", parameters = [7.0, 8.7]},
]
branch = [
    {name = "neutrino_id",   type = "true"},
    {name = "category",      type = "true"},
    {name = "semantic_type", type = "both_particle", selector = "target_michel", selector_parameters = [8.7]},
    {name = "iou",           type = "both_particle", selector = "target_michel", selector_parameters = [8.7]},
    {name = "ke",            type = "both_particle", selector = "target_michel", selector_parameters = [8.7]},
    {name = "calo_ke",       type = "reco_particle", selector = "target_michel", selector_parameters = [8.7]},
    {name = "pdg",           type = "true_particle", selector = "target_michel", selector_parameters = [8.7]},

    { name = "start_x",      type = "both_particle", selector = "target_michel", selector_parameters = [8.7] },
    { name = "start_y",      type = "both_particle", selector = "target_michel", selector_parameters = [8.7] },
    { name = "start_z",      type = "both_particle", selector = "target_michel", selector_parameters = [8.7] },

    { name = "end_x",        type = "both_particle", selector = "target_michel_parent", selector_parameters = [8.7] },
    { name = "end_y",        type = "both_particle", selector = "target_michel_parent", selector_parameters = [8.7] },
    { name = "end_z",        type = "both_particle", selector = "target_michel_parent", selector_parameters = [8.7] },
]

[[tree]]
name = "signal"
sim_only = true
mode = "true"
cut = [
    {name = "!valid_flashmatch", type = "reco"},
    {name = "michel_in_range",   type = "true", parameters = [8.7]},
    {name = "michel_size",       type = "true", parameters = [7.0, 8.7]},
]
branch = [
    {name = "neutrino_id",   type = "true"},
    {name = "category",      type = "true"},
    {name = "semantic_type", type = "both_particle", selector = "target_michel", selector_parameters = [8.7]},
    {name = "iou",           type = "both_particle", selector = "target_michel", selector_parameters = [8.7]},
    {name = "ke",            type = "both_particle", selector = "target_michel", selector_parameters = [8.7]},
    {name = "calo_ke",       type = "reco_particle", selector = "target_michel", selector_parameters = [8.7]},
    {name = "pdg",           type = "true_particle", selector = "target_michel", selector_parameters = [8.7]},

    { name = "start_x",      type = "both_particle", selector = "target_michel", selector_parameters = [8.7] },
    { name = "start_y",      type = "both_particle", selector = "target_michel", selector_parameters = [8.7] },
    { name = "start_z",      type = "both_particle", selector = "target_michel", selector_parameters = [8.7] },

    { name = "end_x",        type = "both_particle", selector = "target_michel_parent", selector_parameters = [8.7] },
    { name = "end_y",        type = "both_particle", selector = "target_michel_parent", selector_parameters = [8.7] },
    { name = "end_z",        type = "both_particle", selector = "target_michel_parent", selector_parameters = [8.7] },
]