# cmake/SetupEnvironment.cmake

# Set paths to external dependencies based on environment variables

set(SBNANA_BASE "$ENV{MRB_INSTALL}/sbnana/$ENV{SBNANA_VERSION}")
set(SBNANAOBJ_BASE "$ENV{MRB_INSTALL}/sbnanaobj/$ENV{SBNANAOBJ_VERSION}")

set(SRPROXY_INC "$ENV{SRPROXY_INC}")
set(OSCLIB_INC "$ENV{OSCLIB_INC}")
set(OSCLIB_LIB "$ENV{OSCLIB_LIB}")
set(EIGEN_INC "$ENV{EIGEN_INC}")

set(SBNANA_INC "$ENV{SBNANA_INC}" CACHE INTERNAL "")
set(SBNANA_LIB "$ENV{SBNANA_LIB}" CACHE INTERNAL "")
set(SBNANAOBJ_INC "$ENV{SBNANAOBJ_INC}" CACHE INTERNAL "")
set(SBNANAOBJ_LIB "$ENV{SBNANAOBJ_LIB}" CACHE INTERNAL "")